language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
before_install:
  - wget https://github.com/wohldad/AI-Genetic-Parallel-Individual/archive/master.zip -O /tmp/individual.zip
  - cd /tmp
  - unzip /tmp/individual.zip
  - cd /tmp/AI-Genetic-Parallel-Individual-master
  - perl Makefile.PL
  - make
  - make test
  - make install
  - make clean
  - cd /tmp
  - wget https://github.com/wohldad/AI-Genetic-Parallel-Population/archive/master.zip -O /tmp/population.zip
  - unzip /tmp/population.zip
  - cd /tmp/AI-Genetic-Parallel-Population-master
  - perl Makefile.PL
  - make
  - make test
  - make install
  - make clean
script: "perl Makefile.PL && make disttest"
